[package]
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>"]
description = "A library to extract content from pdfs"
documentation = "https://docs.rs/crate/pdf-extract/"
edition = "2018"
keywords = ["pdf2text", "text", "pdf", "pdf2txt"]
license = "MIT"
name = "pdf-extract"
repository = "https://github.com/jrmuizel/pdf-extract"
version = "0.7.7"
include = ["src/**/*", "README.md"]

[profile.release]
debug = true

[dependencies]
adobe-cmap-parser = "0.4.0"
encoding_rs = "0.8.34"
euclid = "0.20.5"
lopdf = {version = "0.33", default-features = false, features = ["nom_parser"]}
postscript = "0.14"
type1-encoding-parser = "0.1.0"
unicode-normalization = "0.1.19"
rayon = "1.10.0"
ordered-float = "4.2.2"
ocrs = "0.9.0"
rten = { version = "0.13.1" }
rten-imageproc = { version = "0.13.1" }
rten-tensor = { version = "0.13.1" }
anyhow = "1.0.89"
thiserror = "1.0.63"
fastrand = "2.1.1"
image = { version = "0.25.2", default-features = false, features = ["png", "jpeg", "webp"] }
lexopt = "0.3.0"
miniz_oxide = "0.8.0"
regex = "1.11.1"
lazy_static = "1.5.0"
text-splitter = { version = "0.27.0", features = ["tiktoken-rs"] }
tiktoken-rs = "0.7"

[dev-dependencies]
ureq = "2.6.2"
