[package]
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>"]
description = "A library to extract content from pdfs"
documentation = "https://docs.rs/crate/pdf-extract/"
edition = "2018"
keywords = ["pdf2text", "text", "pdf", "pdf2txt"]
license = "MIT"
name = "pdf-extract"
repository = "https://github.com/jrmuizel/pdf-extract"
version = "0.7.7"
include = ["src/**/*", "README.md"]

[profile.release]
debug = true

[dependencies]
adobe-cmap-parser = "0.4.0"
encoding_rs = "0.8.34"
euclid = "0.20.5"
lopdf = {version = "0.36", default-features = false}
postscript = "0.14"
type1-encoding-parser = "0.1.0"
unicode-normalization = "0.1.19"
rayon = "1.10.0"
ordered-float = "4.2.2"
ocrs = {git="https://github.com/robertknight/ocrs", rev="4a29345"}
rten = { version = ">= 0.14.0, < 0.21.0" }
rten-imageproc = { version = ">= 0.14.0, < 0.21.0" }
rten-tensor = { version = ">= 0.14.0, < 0.21.0" }
anyhow = "1.0.98"
thiserror = "2.0.12"
fastrand = "2.3.0"
image = { version = "0.25.5", default-features = false, features = ["png", "jpeg", "webp"] }
lexopt = "0.3.1"
miniz_oxide = "0.8.0"
regex = "1.11.1"
lazy_static = "1.5.0"
text-splitter = { version = "0.27.0", features = ["tiktoken-rs"] }
tiktoken-rs = "0.7"
unicode-segmentation = "1.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
blake3 = "1.5"
zstd = "0.13"
log = "0.4"
env_logger = "0.11"

[dev-dependencies]
ureq = "2.6.2"
