#!/usr/bin/env python3
"""Regenerate the reportlab PDFs that pdf-extract returns 0 chars for.

These are the exact synthetic docs used by the RZN backend Phase-1 e2e ingest
(search-to-card-index-smoke). The backend's fetch_and_parse -> pdf-extract path
reported `parse_quality_failed: status=empty_text extracted_chars=0` on both
variants below, while `pdftotext` (poppler) extracts ~664 chars from the same
files. Real legal PDFs extract fine. Goal: root-cause why pdf-extract yields 0.

    pip install reportlab   # bundles Vera.ttf (DejaVu Sans)
    python3 generate.py
"""
import io, os, textwrap, reportlab
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
PARAS = [
    "Synthetic test document generated by the RZN end-to-end Phase-1 pipeline check. It exercises source ingest, parse, and archival only, and contains no real legal content.",
    "The petitioner contended that the right to privacy is intrinsic to the right to life and personal liberty. The respondent argued that reasonable restrictions apply under due process of law and the doctrine of proportionality.",
    "Held: the synthetic court records these paragraphs so that the document parser produces multiple distinct passages, which are then archived into the raw payload store as compressed JSONL with a stable content digest.",
]

def render(path, font_name, title):
    c = canvas.Canvas(path, pagesize=letter); y = 750
    c.setFont(font_name, 14); c.drawString(72, y, title); y -= 28
    c.setFont(font_name, 11)
    for p in PARAS:
        for line in textwrap.wrap(p, 88):
            c.drawString(72, y, line); y -= 15
            if y < 72: c.showPage(); y = 750; c.setFont(font_name, 11)
        y -= 10
    c.showPage(); c.save()

# Variant A: base-14 Helvetica (no embedded font, no ToUnicode CMap)
render(os.path.join(HERE, "reportlab_base14_helvetica.pdf"), "Helvetica",
       "RZN E2E Phase-1 Synthetic Judgment (base-14 Helvetica)")

# Variant B: embedded TrueType (DejaVu/Vera) with ToUnicode CMap
vera = os.path.join(os.path.dirname(reportlab.__file__), "fonts", "Vera.ttf")
pdfmetrics.registerFont(TTFont("Vera", vera))
render(os.path.join(HERE, "reportlab_embedded_vera.pdf"), "Vera",
       "RZN E2E Phase-1 Synthetic Judgment (embedded Vera TTF)")

with open(os.path.join(HERE, "expected_text_excerpt.txt"), "w") as f:
    f.write("\n\n".join(PARAS) + "\n")
print("generated:", *sorted(os.listdir(HERE)))
